name: Python application

on:
  workflow_dispatch:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKERPW }}" | docker login -u "kube" --password-stdin harbor.uzhgorod.co.ua/gitops
        docker image build -t harbor.uzhgorod.co.ua/gitops/gitops:hellov1.0 .
        docker push harbor.uzhgorod.co.ua/gitops/gitops:hellov1.0
